config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 5000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    #render plain: params[:article].inspect #to display the hash/passed variables of the form in browser
    @article = Article.new(article_params)
  
    if @article.save
      flash[:notice] = "Your article was created."
      redirect_to article_path(@article)
    else
      render 'new'
    end
    
  end
  
  def edit
    #@article = Article.find(params[:id])
  end
  
  def update
    #@article = Article.find(params[:id])
    
    if @article.update(article_params)
      flash[:notice] = "Your article was updated."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
    
  end
  
  def show
    #@article = Article.find(params[:id])
  end
  
  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
      flash[:notice] = "Your article was deleted."
      redirect_to articles_path
  end
  
  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<p><%= link_to 'Back to Articles', articles_path, class: "btn btn-success btn-sm" %></p>
<% if @article.errors.any? %>
  <h3>The following errors prevented the new article from being created...</h3>
  <ul>
  <% @article.errors.full_messages.each do |message|  %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
        <%= f.text_area :description, rows: 15,  class: "form-control", placeholder: "Article content" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-6 col-sm-7">
          <%= f.submit class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="jumbotron">
    <h1>Edit an Article</h1>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="jumbotron">
  <h1>Your Articles</h1>
  <p><%= link_to 'Create New Article', new_article_path, class: "btn btn-success btn-sm" %></p>
  <table class="table table-bordered table-hover" width="450">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td style="white-space: pre-wrap;"><%= article.description %></td>
      <td><%= link_to 'view', article_path(article), class: "btn btn-success btn-xs" %></td>
      <td><%= link_to 'edit', edit_article_path(article), class: "btn btn-success btn-xs" %></td>
      <td><%= link_to 'delete', article_path(article), class: "btn btn-success btn-xs", method: :delete, data: {confirm: "You are about to delete this article. Are you sure you wish to continue?"} %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<div class="jumbotron">
    <h1>Create an Article</h1>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="jumbotron">
    <h1>Your Selected Article</h1>
    <p><%= link_to 'Back to Articles', articles_path, class: "btn btn-success btn-sm" %></p>
    <h3><%= @article.title %></h3>
    <p style="white-space: pre-wrap;"><%= @article.description %></p>
    <div class="col-md-offset-10 col-md-12">
        <%= link_to 'Edit this article', edit_article_path(@article.id), class: "btn btn-success btn-sm" %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container footer-container">
        <small>
            Spritle, LLC | All rights reserved | © 2005 ~ 2016&nbsp;&nbsp;by <a href="mailto:dpereira@machfive.net">David Pereira</a>
        </small>
        <nav>
            <ul>
                <li><%= link_to 'Home', root_path %></li>
                <li><%= link_to 'About', about_path %></li>
                <li><%= link_to 'Contact', contact_path %></li>
                <li><%= link_to 'Articles', articles_path %></li>
            </ul>
        </nav>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name,message| %>
  <ul>
    <li><%= message %></li>
  </ul>
<% end %>
  

app/views/layouts/_navigation.html.erb
<!--original nav
<ul class="nav nav-tabs">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
    <li><%= link_to 'Articles', articles_path %></li>
</ul>
-->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("logo.png"), root_path, class: "navbar-brand", id: "logo") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Articles<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View all Articles', articles_path %></li>
            <li><%= link_to 'Create a New Article', new_article_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right" id="login">
        <button type="submit" class="btn btn-success">Login</button>
      </form>
      <form class="navbar-form navbar-right" role="search" id="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>David's Rails Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1>About</h1>
  <p>This is the About page for the Udemy Complete Ruby on Rails course's Alpha-Blog project. Click the Articles button above to view, create, update, or delete your articles.</p>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
  <h1>Contact</h1>
  
  <p>
    This is the Contact page for the Udemy Complete Ruby on Rails course's Alpha-Blog project. Click the Articles button above to view, create, update, or delete your articles.
  </p>
  <p>
    <a href="mailto:dpereira@machfive.net">dpereira@machfive.net</a>
  </p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
  <h1>Welcome!</h1>
  <p>This is the Udemy Complete Ruby on Rails course's Alpha-Blog project. Click the View Articles button below to view, create, update, or delete your articles.</p>
  <p><a class="btn btn-success btn-lg btn-xlg" href="<%= articles_path %>" role="button">Sign Up!</a></p>
</div>